### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by SylvKT** [cole14/rust-elf#19]
This crate can be very useful in environments where the standard library is not accessible (i.e. bootloaders and kernels).

**Comment by cole14** [comment]
I've added a default std feature which can be disabled to provide for no_std builds. The parsing is tested and it builds just fine without std, but I haven't actually tried to build another crate that uses it in a no_std environment.

If you have any suggestions for improvements to the interface to make it more useful for these no_std environments (or run into any problems using it), please do open another issue! :)
