### ISSUE TITLE
Implement ReadBytesAt for owned CachedReadBytes

### ISSUE THREAD

**Issue by pjht** [cole14/rust-elf#21]
Right now, `ReadBytesAt` is only implemented for a mutable reference to a `CachedReadBytes`. This requires an extra variable to hold the `CachedReadBytes` instead of passing it directly to `File::open_stream`. Ideally, `ReadBytesAt` would also be implemented for an owned `CachedReadBytes`, allowing it to be passed directly.

**Comment by cole14** [comment]
Thanks for the suggestion, what do you think of #22?

**Comment by pjht** [comment]
Looks good, that would accomplish what I wanted.

**Comment by cole14** [comment]
Cool. I bundled this change into crate v0.4.0.
