### ISSUE TITLE
Offset checking

### ISSUE THREAD

**Issue by pinkforest** [cole14/rust-elf#23]
@cole14 

Could we please provide feedback on: https://github.com/rustsec/advisory-db/pull/1450

The maintainer input would be most crucial to this potential advisory - whether accepted or not.

Cheers

**Comment by cole14** [comment]
Looks like that advisory is actually for the [elf_rs crate](https://crates.io/crates/elf_rs), which is a different crate and is found [here](https://github.com/vincenthouyi/elf_rs).

**Comment by cole14** [comment]
I'm going to close this specific issue. I'd love to see some fuzzing done on this crate, too, and it's on my list to work on eventually. If you end up fuzzing this crate and finding issues, please open a new issue! :)
