### ISSUE TITLE
Your docs proudly say "no unsafe code" but `core` is full of unsafe

### ISSUE THREAD

**Issue by Lokathor** [cole14/rust-elf#30]
I say this as the owner of both "one of those transmutation libraries" and also a crate that proudly is a forbid(unsafe_code) crate: Saying so strongly that you don't use any unsafe code ever, not even burried in your deps, and then implying that it gives some advantage over folks who do use an unsafe-wrapping crate such as zerocopy, it's an unrealistic claim. Because you're using `core` for the slices after all, and slices are all kinds of unsafe internally.

So I guess the short summary of the issue might be "would you mind easing up on the wording there?"

**Comment by cole14** [comment]
I'm happy to update that text and can see how it can be read as inflammatory (though that was not my intent). When writing that piece, I was mainly thinking of some other ELF parser crates out there that have actual unsafe code blocks that use unsafe core functions to do slice transmutes that result in undefined behavior and crashes on bad ELF data. My intent wasn't to disparage crates like bytemuck or zerocopy.

**Comment by cole14** [comment]
How about something simpler like:

✨ Uses only safe interfaces ✨

With memory safety a core goal, this crate contains zero unsafe code blocks of its own and only uses safe interface methods from core and std, so you can trust in rust's memory safety guarantees without also having to trust this library developer as having truly been "right" in why some unsafe block was safe. 💃

Note: I'd love to see this crate be enhanced further once rust provides safe transmutes.

See https://github.com/rust-lang/project-safe-transmute

**Comment by Lokathor** [comment]
That sounds great.

And i wouldn't even call the current wording inflammatory, just that I know a lot of non-Rust programmers who feel like Rust folks can end up "over promising". So it doesn't hurt, as a Rust community, to temper expectations a hair.

**Comment by cole14** [comment]
Ok, it's been updated. Thanks for the feedback!
