### ISSUE TITLE
Dyn accessors move out of self

### ISSUE THREAD

**Issue by Docteur-Lalla** [cole14/rust-elf#34]
Hello,

Writing from the version 0.7.3 perspective, the struct `elf::dynamic::Dyn` has two reader methods named `d_val` and `d_ptr`. Both of them take `self` by value (and thus move out of it), instead of taking it by reference. This means that in order to get the information, we need to abandon the `Dyn` object. Is there a reason for that or is it a mistake?

Best regards.

**Comment by cole14** [comment]
Thanks for the report. That's not intentional and should be by reference as you point out.
